name: "mnist_model_openvino"
platform: "openvino"
backend: "openvino"
max_batch_size: 0

input [
  {
    name: "input.1"
    data_type: TYPE_FP32
    dims: [-1, 1, 28, 28]
  }
]

output [
  {
    name: "18"
    data_type: TYPE_FP32
    dims: [-1, 10]
  }
]

instance_group [
  {
    kind: KIND_CPU
  }
]
