version: "3.8"

services:
  fastapi_app:
    build:
      context: ./app
    networks:
      - my_network
    ports:
      - "5000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount the Docker socket
      - /home/atharav/react/docker_app/storage/permanent_storage:/home/atharav/react/docker_app/app/permanent_storage
      - /home/atharav/react/docker_app/storage/training_images:/home/atharav/react/docker_app/app/training_images
      - clientfiles:/home/atharav/react/docker_app/app/clientfiles
      - retrainfiles:/home/atharav/react/docker_app/app/retrainfiles
      - model_repository:/home/atharav/react/docker_app/app/model_repository

  client:
    build:
      context: ./client
    networks:
      - my_network
    ports:
      - "3000:3000"

  admin:
    build:
      context: ./admin
    networks:
      - my_network
    ports:
      - "3001:3000"

networks:
  my_network:
    driver: bridge

volumes:
  model_repository:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/atharav/react/docker_app/model_repository
  retrainfiles:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/atharav/react/docker_app/files/retrainfiles
  clientfiles:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/atharav/react/docker_app/files/clientfiles
